name: Copilot Setup Steps

permissions:
  contents: read

on:
  push:
  workflow_dispatch:  # Allows manual runs

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and package
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libportaudio2
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e .[dev]